import type { CompanyEvent, CompanySpot } from "@/types/company";

export const sampleCompanySpots: CompanySpot[] = [
  {
    id: "sample-ramen-station",
    name: "Ramen near the station",
    category: "food",
    comment: "I want to try this with coworkers.",
    imageUrl: null,
    mapX: 65,
    mapY: 55,
    lat: null,
    lng: null,
    language: "en",
    createdBy: null,
    createdAt: new Date(0).toISOString(),
    interestCount: 12,
  },
  {
    id: "sample-sakura-park",
    name: "Peaceful sakura park",
    category: "nature",
    comment: "I want to see cherry blossoms here.",
    imageUrl: null,
    mapX: 56,
    mapY: 43,
    lat: null,
    lng: null,
    language: "en",
    createdBy: null,
    createdAt: new Date(0).toISOString(),
    interestCount: 8,
  },
  {
    id: "sample-filipino-restaurant",
    name: "Filipino restaurant",
    category: "comfort",
    comment: "This place made me feel at home.",
    imageUrl: null,
    mapX: 39,
    mapY: 74,
    lat: null,
    lng: null,
    language: "en",
    createdBy: null,
    createdAt: new Date(0).toISOString(),
    interestCount: 6,
  },
  {
    id: "sample-local-festival",
    name: "Local summer festival",
    category: "culture",
    comment: "I want to go to a Japanese festival.",
    imageUrl: null,
    mapX: 47,
    mapY: 66,
    lat: null,
    lng: null,
    language: "en",
    createdBy: null,
    createdAt: new Date(0).toISOString(),
    interestCount: 4,
  },
  {
    id: "sample-sea-view-walk",
    name: "Sea view walk",
    category: "place",
    comment: "This looks like a calm place to walk together.",
    imageUrl: null,
    mapX: 28,
    mapY: 68,
    lat: null,
    lng: null,
    language: "en",
    createdBy: null,
    createdAt: new Date(0).toISOString(),
    interestCount: 3,
  },
];

export const sampleCompanyEvents: CompanyEvent[] = [
  {
    id: "sample-ramen-lunch-event",
    spotId: "sample-ramen-station",
    title: "Ramen lunch at Ramen near the station",
    description: "A small lunch event for coworkers who want to try ramen together.",
    eventDate: null,
    eventTime: "12:00",
    capacity: 12,
    createdAt: new Date(0).toISOString(),
    participantCount: 8,
    spot: sampleCompanySpots[0],
  },
];
